version: "3"

services:
  pihole:
    container_name: pihole
    image: docker.io/firewalla/pihole:latest
    ports:
      - "%FW_PIHOLE_TCP_PORT%:53/tcp"
      - "%FW_PIHOLE_UDP_PORT%:53/udp"
    environment:
      TZ: '%FW_TIMEZONE%'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
    restart: unless-stopped