#!/bin/bash
sync

: ${FIREWALLA_HOME:=/home/pi/firewalla}
source ${FIREWALLA_HOME}/platform/platform.sh

bro_process_cnt=`ps -ef |grep "$(bro_proc_name)ctl/auto" | grep -v grep | wc -l`
if [[ $bro_process_cnt -lt 3 ]]; then
    logger 'FIREWALLA: bro-quick-cron: bro restart due to bro vanished'
    sudo service brofish stop
    sudo service brofish start
fi
