#!/bin/bash
sync

mem=$(free -m | awk '/-/{print $4}')

/home/pi/firewalla/scripts/free-memory-process

(( mem <= 0 )) && mem=$(free -m | awk '/Mem:/{print $7}')
(( mem <= 511 )) && logger "FIREWALLA: Memeory Critical Simulation "+$mem
(( mem <= 30 )) && logger "FIREWALLA: Memory reboot"+$mem
(( mem <= 30 )) && curl http://localhost:8834/v1/system/perfstat 2>/dev/null >> /home/pi/.forever/top_before_reboot.log
(( mem <= 30 )) &&  /home/pi/firewalla/scripts/fire-reboot
(( mem <= 55 )) && /home/pi/firewalla/scripts/free-memory

disk=$(df -k /bspool | tail -1 | awk '{print $4}')
(( disk <= 5000 )) && logger "FIREWALLA: Disk Delete "+$disk
(( disk <= 5000 )) && sudo /usr/local/bro/bin/broctl cron
(( disk <= 5000 )) && sudo rm -r -f /bspool/bro/*-*_*.log

if mount | grep overlay &>/dev/null; then
  # overlay fs uses a separate disk for logs
  FREE=`df -k --output=avail "/log" | tail -n1`   # df -k not df -h
  if [[ $FREE -lt 100000 ]]; then               # 100M
    /home/pi/firewalla/scripts/clean-disk
  fi;
else
  FREE=`df -k --output=avail "/home" | tail -n1`   # df -k not df -h
  if [[ $FREE -lt 1000000 ]]; then               # 1G
    /home/pi/firewalla/scripts/clean-disk
  fi;
fi
