#!/bin/bash
sync

: ${FIREWALLA_HOME:=/home/pi/firewalla}
source ${FIREWALLA_HOME}/platform/platform.sh

bro_process_cnt=`ps -ef |grep "${BRO_PROC_NAME}ctl/auto" | grep -v grep | wc -l`
if [[ $bro_process_cnt -lt $BRO_PROC_COUNT ]]; then
    logger "FIREWALLA: bro-bro-check: ${BRO_PROC_NAME} restart due to ${BRO_PROC_NAME} vanished"
    sudo service brofish stop
    sudo service brofish start
fi
