#!/bin/bash
sync
#/usr/bin/sudo /bin/rm -r -f /bspool/bro/*-*_*.log
/usr/bin/sudo /bin/rm -r -f /bspool/tmp/post-terminate*
/usr/bin/sudo /bin/rm -r -f /bspool/tmp/*
#node /home/pi/firewalla/scripts/clean-redis.js &

ui_process_cnt=`sudo systemctl status fireui | grep 'active (running)' | wc -l`
kickui_process_cnt=`sudo systemctl status firekick |grep 'active (running)' | wc -l`
api_process_cnt=`sudo systemctl status fireapi |grep 'active (running)' | wc -l`
if [[ $ui_process_cnt -lt 1 ]]; then
    if [[ $kickui_process_cnt -lt 1 ]]; then
        if [[ $api_process_cnt -lt 1 ]]; then
            logger 'FIREWALLA: no ui process'
        fi
    fi
fi
