#!/bin/bash
sync

mem=$(free -m | awk '/-/{print $4}')
firemon_mem=$(pidof FireMon | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
fireapi_mem=$(pidof FireApi | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
firemain_mem=$(pidof FireMain | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
(( firemon_mem >= 80000)) && logger "FIREWALLA: Firemon Critical Memory"+firemon_mem
(( firemon_mem >= 100000)) && logger "FIREWALLA: Firemon Critical Memory Restart"+firemon_mem
(( firemon_mem >= 100000)) && sudo service firemon restart
(( firemain_mem >= 80000)) && logger "FIREWALLA: FireMain Critical Memory"+firemain_mem
(( firemain_mem >= 100000)) && logger "FIREWALLA: FireMain Critical Memory Restart"+firemain_mem
(( firemain_mem >= 100000)) && sudo service firemain restart
(( fireapi_mem >= 80000)) && logger "FIREWALLA: FireApi Critical Memory"+fireapi_mem
(( fireapi_mem >= 100000)) && logger "FIREWALLA: FireApi Critical Memory Restart"+fireapi_mem
(( fireapi_mem >= 100000)) && sudo service fireapi restart

(( mem <= 0 )) && mem=$(free -m | awk '/Mem:/{print $7}')
(( mem <= 511 )) && logger "FIREWALLA: Memeory Critical Simulation "+$mem
(( mem <= 40 )) && logger "FIREWALLA: Memory reboot"+$mem
(( mem <= 40 )) && curl http://localhost:8834/v1/sys/perfstat 2>/dev/null >> /home/pi/.forever/top_before_reboot.log
(( mem <= 40 )) &&  /home/pi/firewalla/scripts/fire-reboot
(( mem <= 65 )) && /home/pi/firewalla/scripts/free-memory

disk=$(df -k /bspool | tail -1 | awk '{print $4}')
(( disk <= 5000 )) && logger "FIREWALLA: Disk Delete "+$disk
(( disk <= 5000 )) && sudo /usr/local/bro/bin/broctl cron
(( disk <= 5000 )) && sudo rm -r -f /bspool/bro/*-*_*.log
