module.exports = {
  DESKTOP: 'desktop',
  SMARTPHONE: 'smartphone',
  TABLET: 'tablet',
  FEATURE_PHONE: 'feature phone',
  CONSOLE: 'console',
  TV: 'tv',
  CAR_BROWSER: 'car browser',
  SMART_DISPLAY: 'smart display',
  CAMERA: 'camera',
  PORTABLE_MEDIA_PLAYER: 'portable media player',
  PHABLET: 'phablet',
  SMART_SPEAKER: 'smart speaker',
  WEARABLE: 'wearable',
  PERIPHERAL: 'peripheral',
};
