#!/bin/bash

: ${FIREWALLA_HOME:=/home/pi/firewalla}
: ${FIREWALLA_HIDDEN:=/home/pi/.firewalla}

logger 'FIREWALLA.ACLAUDIT Stopping'

# iptables audit chains are flushed by ACLAuditLogPlugin.globalOff() via IptablesControl

sudo rm /etc/rsyslog.d/30-acl-audit.conf
sudo rm /etc/rsyslog.d/32-quic-log.conf
sudo systemctl restart rsyslog

sudo rm $FIREWALLA_HIDDEN/config/crontab/acl-audit-logrotate
sudo rm $FIREWALLA_HIDDEN/config/crontab/quic-logrotate
$FIREWALLA_HOME/scripts/update_crontab.sh

logger 'FIREWALLA.ACLAUDIT Finished Stopping'
