#!/bin/bash

: ${FIREWALLA_HOME:=/home/pi/firewalla}
: ${FIREWALLA_HIDDEN:=/home/pi/.firewalla}

logger 'FIREWALLA.ACLAUDIT Starting'

sudo mkdir -p /alog/
sudo rm -r -f /alog/*
sudo umount -l /alog
sudo mount -t tmpfs -o size=20m tmpfs /alog

# ensure log file is readable
touch /alog/acl-audit.log
sudo chgrp adm /alog/acl-audit.log
sudo chown syslog /alog/acl-audit.log
sudo chmod 644 /alog/acl-audit.log

sudo rm -rf /log/alog
sudo ln -sf /alog /log/alog

mkdir -p $FIREWALLA_HIDDEN/config/crontab/
sudo cp $FIREWALLA_HOME/etc/logrotate.d/acl-audit /etc/logrotate.d/
echo "* * * * * sudo logrotate /etc/logrotate.d/acl-audit" > $FIREWALLA_HIDDEN/config/crontab/acl-audit-logrotate
$FIREWALLA_HOME/scripts/update_crontab.sh

sudo cp ${FIREWALLA_HOME}/etc/rsyslog.d/30-acl-audit.conf /etc/rsyslog.d/
sudo systemctl restart rsyslog

if [[ $(redis-cli hget policy:system acl) == "true" ]]; then
  RULE_POS=3
else
  RULE_POS=1
fi

sudo iptables -w -C FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]" &>/dev/null || sudo iptables -w -I FW_DROP $RULE_POS -j LOG --log-prefix "[FW_ACL_AUDIT]"
sudo ip6tables -w -C FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]" &>/dev/null || sudo ip6tables -w -I FW_DROP $RULE_POS -j LOG --log-prefix "[FW_ACL_AUDIT]"
sudo iptables -w -C FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null || sudo iptables -w -I FW_SEC_DROP $RULE_POS -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo ip6tables -w -C FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null || sudo ip6tables -w -I FW_SEC_DROP $RULE_POS -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo iptables -w -C FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null || sudo iptables -w -I FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo ip6tables -w -C FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null || sudo ip6tables -w -I FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"

logger 'FIREWALLA.ACLAUDIT Finished Starting'
