#!/bin/bash

: ${FIREWALLA_HOME:=/home/pi/firewalla}
: ${FIREWALLA_HIDDEN:=/home/pi/.firewalla}

logger 'FIREWALLA.ACLAUDIT Starting'

# ensure log file is readable
touch /alog/acl-audit.log
sudo chgrp adm /alog/acl-audit.log
sudo chown syslog /alog/acl-audit.log
sudo chmod 644 /alog/acl-audit.log

sudo rm -rf /log/alog
sudo ln -sf /alog /log/alog

mkdir -p $FIREWALLA_HIDDEN/config/crontab/
sudo cp $FIREWALLA_HOME/etc/logrotate.d/acl-audit /etc/logrotate.d/
echo "* * * * * sudo logrotate /etc/logrotate.d/acl-audit" > $FIREWALLA_HIDDEN/config/crontab/acl-audit-logrotate
$FIREWALLA_HOME/scripts/update_crontab.sh

sudo cp ${FIREWALLA_HOME}/etc/rsyslog.d/30-acl-audit.conf /etc/rsyslog.d/
sudo systemctl restart rsyslog

# outbound outgoing packet
sudo iptables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O "
# outbound incoming packet
sudo iptables -w -C FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R "
# inbound outgoind packet
sudo iptables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R "
# inbound incoming packet
sudo iptables -w -C FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O "
# local original packet
sudo iptables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O "
# local reply packet
sudo iptables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R " &>/dev/null || sudo iptables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R "

# outbound outgoing packet
sudo ip6tables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O "
# outbound incoming packet
sudo ip6tables -w -C FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R "
# inbound outgoind packet
sudo ip6tables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R "
# inbound incoming packet
sudo ip6tables -w -C FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O "
# local original packet
sudo ip6tables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O "
# local reply packet
sudo ip6tables -w -C FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R " &>/dev/null || sudo ip6tables -w -A FW_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R "

# outbound outgoing packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O SEC=1 "
# outbound incoming packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R SEC=1 "
# inbound outgoind packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R SEC=1 "
# inbound incoming packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O SEC=1 "
# local original packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O SEC=1 "
# local reply packet
sudo iptables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R SEC=1 "

# outbound outgoing packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O SEC=1 "
# outbound incoming packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R SEC=1 "
# inbound outgoind packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R SEC=1 "
# inbound incoming packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O SEC=1 "
# local original packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O SEC=1 "
# local reply packet
sudo ip6tables -w -C FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R SEC=1 "

# outbound outgoing packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 "
# outbound incoming packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 "
# inbound outgoind packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 "
# inbound incoming packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 "
# local original packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 "
# local reply packet
sudo iptables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 " &>/dev/null || sudo iptables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 "

# outbound outgoing packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 "
# outbound incoming packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 "
# inbound outgoind packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 "
# inbound incoming packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 "
# local original packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 "
# local reply packet
sudo ip6tables -w -C FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 " &>/dev/null || sudo ip6tables -w -A FW_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 "

# outbound outgoing packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 SEC=1 "
# outbound incoming packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 SEC=1 "
# inbound outgoind packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 SEC=1 "
# inbound incoming packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 SEC=1 "
# local original packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 SEC=1 "
# local reply packet
sudo iptables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 SEC=1 " &>/dev/null || sudo iptables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 SEC=1 "

# outbound outgoing packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=O CD=O TLS=1 SEC=1 "
# outbound incoming packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=O CD=R TLS=1 SEC=1 "
# inbound outgoind packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set ! --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=I CD=R TLS=1 SEC=1 "
# inbound incoming packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set ! --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=I CD=O TLS=1 SEC=1 "
# local original packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir ORIGINAL -j LOG --log-prefix "[FW_ADT]D=L CD=O TLS=1 SEC=1 "
# local reply packet
sudo ip6tables -w -C FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_SEC_TLS_DROP_LOG -m set --match-set monitored_net_set src,src -m set --match-set monitored_net_set dst,dst -m conntrack --ctdir REPLY -j LOG --log-prefix "[FW_ADT]D=L CD=R TLS=1 SEC=1 "

sudo iptables -w -C FW_WAN_IN_DROP_LOG -j LOG --log-prefix "[FW_ADT]D=W CD=O SEC=1 " &>/dev/null || sudo iptables -w -A FW_WAN_IN_DROP_LOG -j LOG --log-prefix "[FW_ADT]D=W CD=O SEC=1 "
sudo ip6tables -w -C FW_WAN_IN_DROP_LOG -j LOG --log-prefix "[FW_ADT]D=W CD=O SEC=1 " &>/dev/null || sudo ip6tables -w -A FW_WAN_IN_DROP_LOG -j LOG --log-prefix "[FW_ADT]D=W CD=O SEC=1 "

logger 'FIREWALLA.ACLAUDIT Finished Starting'
