#!/bin/bash

: ${FIREWALLA_HOME:=/home/pi/firewalla}
: ${FIREWALLA_HIDDEN:=/home/pi/.firewalla}

logger 'FIREWALLA.ACLAUDIT Stopping'

sudo iptables -C FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]" &>/dev/null && sudo iptables -D FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]"
sudo ip6tables -C FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]" &>/dev/null && sudo ip6tables -D FW_DROP -j LOG --log-prefix "[FW_ACL_AUDIT]"
sudo iptables -C FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null && sudo iptables -D FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo ip6tables -C FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null && sudo ip6tables -D FW_SEC_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo iptables -C FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null && sudo iptables -D FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"
sudo ip6tables -C FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]" &>/dev/null && sudo ip6tables -D FW_WAN_IN_DROP -j LOG --log-prefix "[FW_SEC_AUDIT]"

sudo rm /etc/rsyslog.d/30-acl-audit.conf
sudo systemctl restart rsyslog

sudo rm $FIREWALLA_HIDDEN/config/crontab/acl-audit-logrotate
$FIREWALLA_HOME/scripts/update_crontab.sh

logger 'FIREWALLA.ACLAUDIT Finished Stopping'
