#!/bin/bash -

: ${FIREWALLA_HOME:=/home/pi/firewalla}
source ${FIREWALLA_HOME}/platform/platform.sh

logger 'FIREWALLA.BROFISH Start '
mkdir /firewalla
chmod 777 /firewalla

/home/pi/firewalla/scripts/firelog -t local -m "FIREWALLA.BRO.DATE.SYNC"
/home/pi/firewalla/scripts/fire-time.sh
logger "FIREWALLA.BRO.DATE.SYNC.DONE"

if [ -f  /bspool/tmp/post-term* ]; then
    echo "bro crashed, reboot"
    logger 'FIREWALLA: restart due to bro crashed'
    rm -r -f /bspool/*
    sync
    /home/pi/firewalla/scripts/fire-reboot
fi
GITHUB_STATUS_API=https://status.github.com/api.json
for i in `seq 1 10`; do
    HTTP_STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" $GITHUB_STATUS_API`
    if [[ $HTTP_STATUS_CODE == "200" ]]; then
      break
    fi
    /home/pi/firewalla/scripts/firelog -t debug -m "FIREWALLA.BRO NO Network"
    sleep 1
done


rm -r -f /blog/*
rm -r -f /bspool/*
umount /bspool
mount -t tmpfs -o size=30m tmpfs /bspool
cd /home/pi/firewalla
cd .git
sudo chown -R pi *
cd ..
branch=$(git rev-parse --abbrev-ref HEAD)

sleep 3

sudo cp etc/bro-cron /etc/cron.hourly/.

sudo cp /home/pi/firewalla/etc/local.bro /usr/local/bro/share/bro/site/local.bro
sync

before_bro

/usr/local/bro/bin/broctl deploy & echo $! > /firewalla/bro.pid
logger "FIREWALLA: Deployed BRO using BROCTL"
sudo cp /home/pi/firewalla/etc/sysctl.conf /etc/sysctl.conf
sudo sysctl -p

logger "FIREWALLA: BRO-RUN Finished"
#(sleep 20; sudo -u pi crontab -r ; sudo -u pi crontab /home/pi/firewalla/etc/brotab)&
