#!/bin/bash -

: ${FIREWALLA_HOME:=/home/pi/firewalla}
source ${FIREWALLA_HOME}/platform/platform.sh

logger 'FIREWALLA.BROFISH Start '
mkdir /firewalla
chmod 777 /firewalla

/home/pi/firewalla/scripts/firelog -t local -m "FIREWALLA.BRO.DATE.SYNC"
/home/pi/firewalla/scripts/fire-time.sh
logger "FIREWALLA.BRO.DATE.SYNC.DONE"

if [ -f  /bspool/tmp/post-term* ]; then
    echo "bro crashed, reboot"
    logger 'FIREWALLA: restart due to bro crashed'
    rm -r -f /bspool/*
    sync
    /home/pi/firewalla/scripts/fire-reboot
fi
GITHUB_STATUS_API=https://status.github.com/api.json
for i in `seq 1 10`; do
    HTTP_STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" $GITHUB_STATUS_API`
    if [[ $HTTP_STATUS_CODE == "200" ]]; then
      break
    fi
    /home/pi/firewalla/scripts/firelog -t debug -m "FIREWALLA.BRO NO Network"
    sleep 1
done


rm -r -f /blog/*
rm -r -f /bspool/*
umount /bspool
mount -t tmpfs -o size=30m tmpfs /bspool
cd /home/pi/firewalla
cd .git
sudo chown -R pi *
cd ..
branch=$(git rev-parse --abbrev-ref HEAD)

sleep 3
#  if [[ $branch =~ release.* ]]
#  then
#    sudo rm -f /home/pi/firewalla/.git/*.lock
#    sudo -u pi git fetch origin $branch
#    sudo -u pi git reset --hard origin/$branch
#    sudo /opt/vc/bin/tvservice -o
#    echo "on release"
#  else
#    echo "on devbranch"
#  fi

## BRO-RUN should NO longer handles upgrade logic
#sudo -u pi git pull
sudo cp etc/bro-cron /etc/cron.hourly/.
#sudo cp /home/pi/firewalla/etc/brofish.service /etc/systemd/system/.
#sudo cp /home/pi/firewalla/etc/firewalla.service /etc/systemd/system/.
#sudo systemctl reenable firewalla
# sudo cp /home/pi/firewalla/etc/firemain.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/firemon.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/firekick.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/fireui.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/fireapi.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/fireupgrade.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/bitbridge4.service /etc/systemd/system/.
# sudo cp /home/pi/firewalla/etc/bitbridge6.service /etc/systemd/system/.

# sudo systemctl reenable fireupgrade
# sudo systemctl daemon-reload
# sudo cp /home/pi/firewalla/etc/broctl.cfg  /usr/local/bro/etc/broctl.cfg
sudo cp /home/pi/firewalla/etc/local.bro /usr/local/bro/share/bro/site/local.bro
sync

before_bro

/usr/local/bro/bin/broctl deploy & echo $! > /firewalla/bro.pid
logger "FIREWALLA: Deployed BRO using BROCTL"
sudo cp /home/pi/firewalla/etc/sysctl.conf /etc/sysctl.conf
sudo sysctl -p

logger "FIREWALLA: BRO-RUN Finished"
#(sleep 20; sudo -u pi crontab -r ; sudo -u pi crontab /home/pi/firewalla/etc/brotab)&
