#!/bin/bash -
cd /home/pi/firewalla
rm /home/pi/.forever/*last.log
cat /dev/null > /home/pi/.forever/main.log
cat /dev/null > /home/pi/.forever/kickui.log
cat /dev/null > /home/pi/.forever/blue.log
cat /dev/null > /home/pi/.forever/ui.log
cat /dev/null > /home/pi/.forever/monitor.log
cat /dev/null > /home/pi/.forever/api.log
cat /dev/null > /home/pi/.forever/dns.log
cat /dev/null > /home/pi/.forever/spoof.log
cat /dev/null > /tmp/forever.out
cat /dev/null > /tmp/forever.log
cat /dev/null > /tmp/forever.err
