#!/bin/bash

: ${FIREWALLA_HOME:=/home/pi/firewalla}
: ${FIREWALLA_HIDDEN:=/home/pi/.firewalla}

source ${FIREWALLA_HOME}/platform/platform.sh

sudo cp $FIREWALLA_HOME/etc/logrotate.d/dnsmasq.logrotate /etc/logrotate.d/dnsmasq
sudo chmod 644 /etc/logrotate.d/dnsmasq

logFile=$FIREWALLA_HIDDEN/config/dnsmasq/log.conf
if [ ! -f "$logFile" ]; then
 touch "$logFile"
 echo "log-facility=/dev/null" > $logFile
fi

logcmd=$1
if [[ $logcmd == "on" ]]; then
        replace_str="log-facility=\/var\/log\/dnsmasq.log"
elif [[ $logcmd == "off" ]]; then
        replace_str="log-facility=\/dev\/null"
fi
sed -i "s/log-facility=.*/$replace_str/" $logFile