#!/bin/bash -
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch =~ release.* ]]; then
    touch /home/pi/.firewalla/managed_reboot
    sync
fi
logger "FIREWALLA REBOOT"
crontab -r
sudo sh -c 'echo V > /dev/watchdog'
sudo sh -c 'echo V > /dev/watchdog'
pkill *fire-ping*
sudo sh -c 'echo V > /dev/watchdog'
sync
sudo reboot
