#!/bin/bash -
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch =~ release.* ]]; then
    touch /home/pi/.firewalla/managed_reboot
    sync
fi
sync
sudo sh -c 'echo V > /dev/watchdog'
sudo reboot
