#!/bin/bash -
logger "FIREWALLA REBOOT NORMAL"
crontab -r
#sudo sh -c 'echo V > /dev/watchdog'
#sudo sh -c 'echo V > /dev/watchdog'
sudo pkill bitbridge*
sudo pkill fire-ping*
sudo pkill sleep*
sleep 2
#sudo sh -c 'echo V > /dev/watchdog'
sync
sync
sync
sync
sudo reboot -f 
