#!/bin/bash -
# This is forced / quick reboot ... something bad just happened

logger "FIREWALLA REBOOT NORMAL FORCED"
#sudo sh -c 'echo V > /dev/watchdog'
#sudo sh -c 'echo V > /dev/watchdog'
sync
crontab -r
sudo pkill fire-ping
sudo pkill -x sleep
sudo pkill fire-ping
sudo pkill fire-watchdog
#sudo sh -c 'echo V > /dev/watchdog'
#sudo sh -c 'echo V > /dev/watchdog'
sudo /home/pi/firewalla/scripts/fake-hwclock
#sudo log2ram write
sync
sync
sync
sync
redis-cli HINCRBY "stats:systemd:restart" system_reboot 1
sudo reboot -f 
