#!/bin/bash -
logger "FIREWALLA REBOOT NORMAL"
/home/pi/firewalla/scripts/fire-stop
touch /home/pi/.firewalla/managed_real_reboot
sync
sync
sync
sync
redis-cli HINCRBY "stats:systemd:restart" system_reboot 1
sudo reboot
