#!/bin/bash -
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch =~ release.* ]]; then
    touch /home/pi/.firewalla/managed_reboot
    sync
fi
logger "FIREWALLA REBOOT FORCED"
/home/pi/firewalla/scripts/fire-reboot-normalf
