#!/bin/bash -
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch =~ release.* ]]; then
    touch /home/pi/.firewalla/managed_reboot
    sync
fi
/home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA REBOOT"
/home/pi/firewalla/scripts/fire-reboot-normal
