#!/bin/bash
#
# -t 'debug' or 'cloud'
# -m message
#

while getopts t:m: option
do
 case "${option}"
 in
 t) DEBUG=${OPTARG};;
 m) MESSAGE=$OPTARG;;
 esac
done

if [[ -e /tmp/FWPRODUCTION ]] 
then  
    if [[ "$DEBUG" != "debug" ]]
    then 
        /usr/bin/logger "FIREWALLA:("$DEBUG"): "$MESSAGE
        echo "FIREWALLA:("$DEBUG"): "$MESSAGE >> /home/pi/logs/Trace.log
    fi
else 
    /usr/bin/logger "FIREWALLA:("$DEBUG"): "$MESSAGE
    echo "FIREWALLA:("$DEBUG"): "$MESSAGE >> /home/pi/logs/Trace.log
fi
