#!/bin/bash -

firemon_pid=$(pidof FireMon)
firemain_pid=$(pidof FireMain)
firemon_mem2=$(pidof FireMon | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
fireapi_mem2=$(pidof FireApi | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
firemain_mem2=$(pidof FireMain | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
redis_mem2=$(pidof redis-server | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
bitbridge7_mem2=$(pidof bitbridge7 | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
bitbridge6_mem2=$(pidof bitbridge6 | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
bro_mem2=$(pidof bro | xargs ps -o rss,sz,vsz | awk 'FNR==2 {print}' | awk '{print $1}')
NOP=`ps -ef |wc -l`
NOT=`ps -aHx | wc -l`
firemain_NOF=`lsof -p $firemain_pid | wc -l`
firemon_NOF=`lsof -p $firemon_pid | wc -l`
NOF=`cat /proc/sys/fs/file-nr`
firemon_threads=$( ps -o nlwp -h $firemon_pid)
firemain_threads=$( ps -o nlwp -h $firemain_pid)

/home/pi/firewalla/scripts/firelog -t debug -m "FIREWALLA: FireApi Critical Memory Restart2 mon:$firemon_mem2, api:$fireapi_mem2, main:$firemain_mem2,bro:$bro_mem2,redis:$redis_mem2,b7:$bitbridge7_mem2,b6:$bitbridge6_mem2,proc:$NOP, thread:$NOT main_thread:$firemain_threads mon_threads:$firemon_threads mainfile:$firemain_NOF monfile:$firemon_NOF sys:$NOF"
#free -m | logger

(( firemain_mem2 >= 140000)) && /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: FireMain Critical Memory Restart2"+$firemain_mem2
(( firemain_mem2 >= 140000)) && sudo service firemain restart
(( firemon_mem2 >= 120000)) && /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: Firemon Critical Memory Restart2"+$firemon_mem2
(( firemon_mem2 >= 120000)) && sudo service firemon restart

if [[ $(uname -m) == "aarch64" ]]; then
       (( fireapi_mem2 >= 140000)) && /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: FireApi Critical Memory Restart2"+$fireapi_mem2
       (( fireapi_mem2 >= 140000)) && ( touch /home/pi/.firewalla/managed_reboot; sudo service fireapi restart )
else
       (( fireapi_mem2 >= 100000)) && /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: FireApi Critical Memory Restart2"+$fireapi_mem2
       (( fireapi_mem2 >= 100000)) && ( touch /home/pi/.firewalla/managed_reboot; sudo service fireapi restart )
fi

if [ $NOP -gt 2000 ]
then
   /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: PROCESS > 2000 REBOOT $NOP"
   /home/pi/firewalla/scripts/fire-rebootf
fi

if [ $NOT -gt 10000 ]
then
   /home/pi/firewalla/scripts/firelog -t cloud -m "FIREWALLA: THREADS > 10000 REBOOT $NOT"
   /home/pi/firewalla/scripts/fire-rebootf
fi

