#!/bin/bash -
logger "FIREWALLA: LAST RESPORT"
redis-cli publish "OldDataCleanSensor" "Start"
sudo service firemon restart
sleep 1
sudo /usr/local/bro/bin/broctl restart
sleep 2 
sudo service firemain restart
#node /home/pi/firewalla/scripts/clean-redis.js &
mem=$(free -m | awk '/-/{print $4}')
(( mem <= 0 )) && mem=$(free -m | awk '/Mem:/{print $7}')
(( mem <= 20 )) && logger "REBOOT: Memory less than 20 $mem"
(( mem <= 20 )) && /home/pi/firewalla/scripts/fire-rebootf
