#!/bin/bash -
if [[ $1 == "full" ]]; then
  logger "FIREWALLA: REDIS FULL DATA CLEAN"
  redis-cli publish "OldDataCleanSensor" "FullClean"
else
  logger "FIREWALLA: REDIS DATA CLEAN"
  redis-cli publish "OldDataCleanSensor" "Start"
fi
sync
