#!/bin/bash -

#
#    Copyright 2017 Firewalla LLC
#
#    This program is free software: you can redistribute it and/or  modify
#    it under the terms of the GNU Affero General Public License, version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

case "$1" in 
    blink)
       sudo sh -c 'echo heartbeat > /sys/devices/platform/leds/leds/nanopi:green:status/trigger'
       sudo sh -c 'echo heartbeat > /sys/devices/platform/leds/leds/nanopi:blue:status/trigger'
       ;;

    off)
       echo "off"
       sudo sh -c 'echo none > /sys/devices/platform/leds/leds/nanopi:green:status/trigger'
       sudo sh -c 'echo none > /sys/devices/platform/leds/leds/nanopi:blue:status/trigger'
       ;;
    
    on)
       sudo sh -c 'echo default-on > /sys/devices/platform/leds/leds/nanopi:green:status/trigger'
       sudo sh -c 'echo default-on > /sys/devices/platform/leds/leds/nanopi:blue:status/trigger'
       ;;
esac
