#!/bin/bash -
: ${FIREWALLA_HOME:=/home/pi/firewalla}

sudo rm -r -f /tmp/*
sudo rm -r -f /home/pi/.forever/*
cd $FIREWALLA_HOME
branch=$(git rev-parse --abbrev-ref HEAD)
cd /tmp 
if [ ! -f $FIREWALLA_HOME/bin/dev ]; then
  if [[ $branch =~ release.* ]]
    then
     cp $FIREWALLA_HOME/bin/real/bitbridge4 $FIREWALLA_HOME/bin/.
     cp $FIREWALLA_HOME/bin/mock/bitbridge6 $FIREWALLA_HOME/bin/.
    else
     cp $FIREWALLA_HOME/bin/real/bitbridge4 $FIREWALLA_HOME/bin/.
     cp $FIREWALLA_HOME/bin/real/bitbridge6 $FIREWALLA_HOME/bin/.
  fi
else
     cp $FIREWALLA_HOME/bin/mock/* $FIREWALLA_HOME/bin/.
fi
nohup sudo ~/firewalla/bin/bitbridge6 -R -l eth0 &
sudo ip6tables -I OUTPUT -p icmpv6 --icmpv6-type redirect -j DROP
cd $FIREWALLA_HOME
if [ ! -f $FIREWALLA_HOME/node_modules/stats-lite/stats.js ]; then
    echo "Updating NPM Stats"
    npm install stats-lite --save
fi
if [ ! -f $FIREWALLA_HOME/node_modules/cron/package.json ]; then
    echo "Updating NPM CRON"
    npm install cron --save
fi
if [ ! -f $FIREWALLA_HOME/node_modules/nat-pmp/package.json ]; then
    echo "Updating NPM CRON"
    npm install nat-pmp 
    npm install nat-upnp 
fi
if [ ! -f $FIREWALLA_HOME/node_modules/mobile-detect/package.json ]; then
    echo "Updating NPM MOBILE-DETECT"
    npm install mobile-detect --save
fi
if [ ! -f $FIREWALLA_HOME/node_modules/socket.io-client/package.json ]; then
    echo "Updating NPM MOBILE-DETECT"
    npm install socket.io-client@1.4.8
fi
if [ ! -f $FIREWALLA_HOME/node_modules/bleno/package.json ]; then
    echo "Updating NPM BLENO"
    sudo cp $FIREWALLA_HOME/config/netbot.config /encipher.config/.
    sudo apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
    npm install bleno --save
    sudo setcap cap_net_raw+eip $(eval readlink -f `which nodejs`)
fi

function check_upgrade {
    PACKAGE_NAME=$1
    if [ ! -f $FIREWALLA_HOME/node_modules/$PACKAGE_NAME/package.json ]; then
        echo "Updating NPM $PACKAGE_NAME"
        npm install $PACKAGE_NAME
    fi
}

check_upgrade external-ip
check_upgrade jsonfile
check_upgrade swagger-node-express
check_upgrade minimist
check_upgrade express
check_upgrade body-parser

if ! fgrep '"version": "0.3.1",' $FIREWALLA_HOME/node_modules/network/package.json &>/dev/null; then
    npm install network@git+https://git@github.com/melvinto/network.git
fi

sudo setcap cap_net_raw+eip $(eval readlink -f `which nodejs`)
cd net2
forever start --uid main main.js
cd ..
cd sys
forever start --uid ui kickstart.js --config /encipher.config/netbot.config
cd ..
cd monitor
forever start --uid monitor MonitorMain.js 
cd ..
sudo /usr/local/bro/bin/broctl cron
sudo /usr/local/bro/bin/broctl cron enable
sync
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
sync
