#!/bin/bash -

#rm ~/.forever/main.log
#rm ~/.forever/monitor.log
#rm ~/.forever/api.log
#rm ~/.forever/ui.log
forever stop main 
sudo sysctl stop fireui
sudo sysctl stop fireapi
sudo sysctl stop firemon
redis-cli KEYS "policy:*" | xargs redis-cli DEL
sync
sudo reboot
