#!/bin/bash -
forever stop main
forever stop monitor
forever stop ui
rm ~/.forever/*
redis-cli flushall
cd /home/pi/firewalla/net2
forever start --uid main main.js
cd ..
cd sys
forever start --uid ui kickstart.js --config /encipher.config/netbot.config
cd ..
cd monitor
forever start --uid monitor MonitorMain.js

