#!/bin/bash -

/home/pi/firewalla/scripts/fire-stop
redis-cli KEYS "policy:*" | xargs redis-cli DEL
redis-cli DEL "policy_active"
redis-cli HDEL "sys:config" "default_c_init_done"
sync
logger "REBOOT: User Reset Policy"
/home/pi/firewalla/scripts/fire-reboot-normal
