#!/bin/bash -
forever stop main
forever stop monitor
forever stop ui
forever stop api
sync
redis-cli flushall
sudo rm -r -f /tmp/*
sudo rm -r -f ~/.forever/*
sudo rm -r -f /blog/*
sudo rm -r -f /bspool/*
sudo rm -r -f ~/ovpns/*
sudo find /var/log -type f -exec /bin/cp /dev/null {} \;
sync
sudo reboot

