#!/bin/bash -

: ${FIREWALLA_HOME:=/home/pi/firewalla}

logger 'FIREWALLA.SURICATA Start'

source /home/pi/.firewalla/run/suricata/listen_interfaces.rc

# a binary delivered as an asset (SuricataControl.tryUpdateSuricataBinary)
# replaces the image's only if it runs; a missing or broken asset leaves the
# image's in use
suricata_bin=/usr/bin/suricata
asset_bin=/home/pi/.firewalla/run/assets/suricata
if [[ -x $asset_bin ]]; then
  if $asset_bin -V &>/dev/null; then
    suricata_bin=$asset_bin
  else
    logger "FIREWALLA.SURICATA $asset_bin failed to run, using $suricata_bin"
  fi
fi

af_packet_args=""
pf_ring_args=""
pf_ring_supported="no"

if [[ $($suricata_bin --build-info | grep "PF_RING support" | awk '{print $3}') == "yes" ]]; then
  pf_ring_supported="yes"
fi

if ! modinfo pf_ring; then
  pf_ring_supported="no"
fi

if [[ -n $LISTEN_INTERFACES ]]; then
  for INTF in $LISTEN_INTERFACES; do
    if [[ $pf_ring_supported == "yes" ]]; then
      # pfring can only be used on ethernet interface
      if [[ $(cat /sys/class/net/$INTF/type) != "1" ]]; then
        af_packet_args="$af_packet_args --af-packet=${INTF}"
      else
        pf_ring_args="$pf_ring_args --pfring=${INTF}"
      fi
    else
      af_packet_args="$af_packet_args --af-packet=${INTF}"
    fi
  done
fi

sudo mkdir -p /log/slog

if [[ -n $af_packet_args ]]; then
  logger "Suricata will run af-packet using $af_packet_args"
  sudo rm -f /var/run/suricata.afpacket.pid # stale pid file may prevent suricata process from starting properly
  sudo $suricata_bin -c /home/pi/.firewalla/run/suricata/suricata.yaml $af_packet_args --pidfile /var/run/suricata.afpacket.pid --set "unix-command.filename=/var/run/suricata.afpacket.socket" -D
fi

if [[ -n $pf_ring_args ]]; then
  logger "Suricata will run pfring using $pf_ring_args"
  sudo rm -f /var/run/suricata.pfring.pid
  sudo $suricata_bin -c /home/pi/.firewalla/run/suricata/suricata.yaml $pf_ring_args --pidfile /var/run/suricata.pfring.pid --set "unix-command.filename=/var/run/suricata.pfring.socket" -D
fi
