#!/bin/bash -
sudo service firemain stop
sudo service firemon stop
/usr/bin/redis-cli flushall
sudo rm -r -f ~/.encipher/*
sudo rm -r -f /tmp/*
sudo rm -r -f ~/.forever/*
sudo rm -r -f /blog/*
sudo rm -r -f /bspool/*
sudo rm -r -f ~/ovpns/*
sudo rm -r -f ~/.firewalla/
sudo usermod --password $(echo firewalla | openssl passwd -1 -stdin) pi
# source the vars file just edited
sudo source ./vars

# Remove any previous keys
sudo ./clean-all
sudo find /var/log -type f -exec /bin/cp /dev/null {} \;
sync
sync

: ${FIREWALLA_POST_RESET_OP:='reboot'}

if [[ $FIREWALLA_POST_RESET_OP == 'shutdown' ]]; then
    logger "SHUTDOWN: User SHUTDOWN"
    : ${FIREWALLA_SHUTDOWN_NORMAL_SCRIPT:=/home/pi/firewalla/scripts/fire-shutdown-normal}

    $FIREWALLA_SHUTDOWN_NORMAL_SCRIPT
else
    logger "REBOOT: User REBOOT"
    : ${FIREWALLA_REBOOT_NORMAL_SCRIPT:=/home/pi/firewalla/scripts/fire-reboot-normal}

    $FIREWALLA_REBOOT_NORMAL_SCRIPT
fi

