#!/bin/bash

#
#    Copyright 2017-2020 Firewalla Inc.
#
#    This program is free software: you can redistribute it and/or  modify
#    it under the terms of the GNU Affero General Public License, version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


: ${FIREWALLA_HOME:='/home/pi/firewalla'}
: ${FIREWALLA_TMP:='/home/pi/tmp'}

mkdir -p $FIREWALLA_TMP
cd $FIREWALLA_TMP
rm -r -f techsupport
mkdir techsupport
cd techsupport
ifconfig > ifconfig.txt
ps -ef > ps.txt
$FIREWALLA_HOME/scripts/status > service_status.txt
top -n 10 -b > top-output.txt
cp -rfp /home/pi/.firewalla .
if [ -z "$1" ]
   then
     cp /data/redis/dump.rdb .
   else
     echo "skip db"
fi
if [ -z "$2" ]
   then
     cp -rfp /home/pi/logs/* .
     sudo cp -p /var/log/syslog* .
   else
     ls -lt /home/pi/logs/FireMon*.log |head -2 | awk '{print $NF}' | xargs -i cp -p {} .
     ls -lt /home/pi/logs/FireApi*.log |head -2 | awk '{print $NF}' | xargs -i cp -p {} .
     ls -lt /home/pi/logs/FireMain*.log |head -2 | awk '{print $NF}' | xargs -i cp -p {} .
     ls -lt /home/pi/logs/FireKick*.log |head -2 | awk '{print $NF}' | xargs -i cp -p {} .
     ls -lt /home/pi/logs/Trace*.log |head -2 | awk '{print $NF}' | xargs -i cp -p {} .
     ls -lt /var/log/syslog* |head -3 | awk '{print $NF}' | xargs -i sudo cp -p {} .
     ls -lt /var/log/openvpn* | awk '{print $NF}' | xargs -i sudo cp -p {} .
     ls -lt /etc/resolv.conf |head -1 | awk '{print $NF}' | xargs -i sudo cp -p {} .
fi
sudo chmod 777 syslog*
cp -rfp /home/pi/.forever/* .
/home/pi/firewalla/scripts/sanity_check.sh > scc.log
curl -s "http://localhost:8837/v1/config/active" &> frcc.log
cd ..
tar -zcvf support.tar.gz techsupport
rm -r -f techsupport
