#!/bin/bash -
/home/pi/firewalla/scripts/fire-stop
sync
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch =~ release.* ]]
  then
    echo "on release"
    cd /home/pi/firewalla
    sudo -u pi git fetch origin $branch
    sudo -u pi git reset --hard origin/$branch
    sudo -u pi git pull
    cd /home/pi/.node_modules
    sudo -u pi git fetch origin $branch
    sudo -u pi git reset --hard origin/$branch
    sudo -u pi git pull
  else
    echo "on devbranch"
  fi
sync
sync
logger "REBOOT: Upgrade"
/home/pi/firewalla/scripts/fireupgrade_hard.sh
