#!/bin/bash

TEMP_FILE=/tmp/firereset-getDHCPLease

# sanitize URL
if [[ "$1" == *"/"* ]]; then
  >&2 echo "Invalid input: "$1
  exit 1
fi

HTTP_CODE=$(curl --request GET \
  --url http://localhost:8837/v1/config/dhcp_lease/$1 \
  --header 'Content-Type: application/json' \
  -sS -N --output $TEMP_FILE \
  --write-out "%{http_code}")

if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
  # stderr will show in firereset log but not returned to client
  >&2 cat $TEMP_FILE
  exit 1
fi

cat $TEMP_FILE | jq -c ".info"
rm $TEMP_FILE
