#!/bin/bash

TEMP_FILE=/tmp/firereset-renewDHCPLease

HTTP_CODE=$(curl --request POST \
  --url http://localhost:8837/v1/config/renew_dhcp_lease \
  --header 'Content-Type: application/json' \
  --data "{ \"intf\": \"$1\" }" \
  -sS -N --output $TEMP_FILE \
  --write-out "%{http_code}")

if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
  # stderr will show in firereset log but not returned to client
  >&2 cat $TEMP_FILE
  exit 1
fi

cat $TEMP_FILE | jq -c ".info"
rm $TEMP_FILE
